config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'problems' => 'problems#index'	#入力画面
  post 'problems/confirm' => 'problems#confirm'	#確認画面
  post 'problems/thanks' => 'problems#thanks'	#送信完了画面

  root to: 'problems#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/problem.rb
class Problem < ApplicationRecord
	include ActiveModel::Model
	
	attr_accessor :name, :email, :message
	validates :name, :presence => {:message => '名前を入力してください'}
	validates :email, :presence => {:message => 'メールアドレスを入力してください'}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	def index
		@problem = Problem.new
		render :action => 'index'
	end
	
	def confirm
		@problem = Problem.new(problem_params)
		if @problem.valid?
			#確認画面表示
			render :action => 'confirm'
		else 
			#エラー。元の画面へ
			render :action => 'index'
		end
	end
	
	def thanks
		@problem = Problem.new(problem_params)
		ProblemMailer.received_email(@problem).deliver

		render :action => 'thanks'
	end

	private
	def problem_params
		params.require(:problem).permit(:name,:email,:message)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/inquirys_helper.rb
module InquirysHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inquiry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/problems/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>

<p><%= link_to "<<Back" , problems_path%></p>
 
<%= form_for @problem, :url => problems_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @problem.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @problem.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@problem.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/problems/index.html.erb
<%= form_for @problem, :url => problems_confirm_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
  </div>
 
  <% if @problem.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @problem.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <table class="table">
    <tr>
      <th>名前<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message %></td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>

app/views/problems/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p><%= link_to "<<Home" , problems_path%></p>
<p>
  お問い合わせいただきありがとうございました。
</p>